[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "indolent"
requires-python = "^3.13"
dynamic = [ "dependencies" ]

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
sqlalchemy = "^2.0.44"
invoke = "^2.2.1"

[tool.poetry.group.dev]
include-groups = [
    "test",
    "format",
    "lint",
]

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.5.0"

[tool.poetry.group.test.dependencies]
pytest = "^9.0.2"
coverage = "^7.13.0"

[tool.poetry.group.format.dependencies]
black = "^25.12.0"
isort = "^7.0.0"

[tool.poetry.group.lint.dependencies]
pylint = "^4.0.4"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.pylint.format]
max-line-length = "88"
